# Makefile for the KhetAI lib as a shared object
# Used for hot reloading while the GUI is running

# Compiler settings
CC = gcc
CFLAGS = -std=c11 -fPIC -O3 -MMD -MP

# Source directory
SRC_DIR = ../../

# Build directory
BUILD_DIR = build_khetai

# Source files
SRC = $(SRC_DIR)khetai_lib.c

# Object files
OBJ = $(BUILD_DIR)/khetai_lib.o

# Library name
LIB = libkhetai.so

# Default target
all: $(BUILD_DIR) $(LIB)

# Create the build directory
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# Compile the library
$(LIB): $(OBJ)
	$(CC) -shared -o $@ $^ $(CFLAGS)

# Compile C source files into object files
$(BUILD_DIR)/%.o: $(SRC_DIR)%.c
	$(CC) -c $< -o $@ $(CFLAGS)

# Include generated dependency files
-include $(OBJ:.o=.d)

# Clean target
clean:
	rm -f $(OBJ) $(LIB) $(BUILD_DIR)/*.d
	rm -rf $(BUILD_DIR)

.PHONY: all clean